title: UBU
colors:
  default:
    - '337ab7'
    - '5cb85c'
    - '5bc0de'
    - 'f0ad4e'
    - 'd9534f'
  pack:
     - 'DD1E2F'
     - 'EBB035'
     - '06A2CB'
     - '218559'
     - 'D0C6B1'
     - '192823'
  light:
     - 'ED5314'
     - 'FFB92A'
     - 'FEEB51'
     - '9BCA3E'
     - '3ABBC9'
     - 'E6E6E6'
  brown:
     - 'A75C56'
     - 'AE695A'
     - 'E89C84'
     - 'F5C972'
     - 'EAB06E'
     - 'C3B274'
  pink:
     - 'C5AAF5'
     - 'A3CBF1'
     - '79BFA1'
     - 'F5A352'
     - 'FB7374'
     - '423C40'


agroups:
  - name: Povezave
    palette: pack
    items:
      - name: Vreme koseze
        url: /vreme
        link: http://vreme.zajcek.org/koseze/
        description: Vremenska postaja Koseze
        icon: fa-cloud

      - name: Radarska slika padavin
        url: /dez
        link: http://www.arso.gov.si/vreme/napovedi%20in%20podatki/radar_animacija.html
        description: ARSO radarska slika padavin animacija
        icon: fa-umbrella

      - name: OŠ Koseze
        url: /sola
        link: http://www.oskoseze.si
        description: Osnovna šola Koseze
        icon: fa-pencil

      - name: Matematika
        url: /matematika
        link: http://astra.si
        description: Posnetki za učenje matematike
        icon: fa-area-chart



  - name: Homelab
    palette: pink
    items:
      - name: PFsense
        url: /pfsense
        link: http://192.168.3.1
        description: Router & firewal
        icon: fa-ban

      - name: Deluge
        url: /deluge
        link: http://192.168.3.4:8112
        description: Bittorrent client
        icon: fa-download

      - name: Bittorrent sync
        url: /btsync
        link: http://192.168.3.4:8888
        description: Bittorrent sync
        icon: fa-cloud-download

      - name: Flexget
        url: /flexget
        link: http://192.168.3.4:5050
        description: Flexget
        icon: fa-download

      - name: Unifi
        url: /unifi
        link: http://192.168.3.4:8080
        description: Unifi wireless manager
        icon: fa-wifi

      - name: Diskstation
        url: /diskstation
        link: http://192.168.3.2
        description: Synology NAS
        icon: fa-server

      - name: MAX
        url: /max
        link: http://192.168.3.4:44444
        description: Max! Eq-3 radiatorji
        icon: fa-thermometer-half

      - name: TP-Link TL-SG2216
        url: /switch
        link: http://192.168.3.170
        description: 16-port switch
        icon: fa-server

      - name: ESXi
        url: /esxi
        link: http://192.168.3.160
        description: ESXI server
        icon: fa-server
